Repository ethersphere/swarm-cli, pull requests merged in 2024-06, with the labels that each got.

#503 feat: merge api
  .github/workflows/ci.yaml
  README.md
  jest.config.ts
  package-lock.json
  package.json
  src/command/addresses.ts
  src/command/cheque/cashout.ts
  src/command/cheque/cheque-command.ts
  src/command/cheque/deposit.ts
  src/command/cheque/withdraw.ts
  src/command/feed/feed-command.ts
  src/command/feed/print.ts
  src/command/feed/update.ts
  src/command/feed/upload.ts
  src/command/manifest/add.ts
  src/command/manifest/create.ts
  src/command/manifest/merge.ts
  src/command/manifest/remove.ts
  src/command/manifest/sync.ts
  src/command/pss/send.ts
  src/command/root-command/command-config.ts
  src/command/root-command/index.ts
  src/command/stake.ts
  src/command/stamp/buy.ts
  src/command/stamp/dilute.ts
  src/command/stamp/list.ts
  src/command/stamp/show.ts
  src/command/stamp/stamp-command.ts
  src/command/stamp/topup.ts
  src/command/status.ts
  src/command/upload.ts
  src/command/utility/unlock.ts
  src/config.ts
  src/service/stamp/index.ts
  test/command/cheque.spec.ts
  test/command/stamp.spec.ts
  test/command/status.spec.ts
  test/misc/config.spec.ts
  test/misc/monetary-units.spec.ts
  test/misc/unavailable-bee-debug.spec.ts
  test/misc/unsure-bee-debug.spec.ts
  test/utility/address.ts
  test/utility/stamp.ts
Labels: pull-request

#504 chore: release 2.10.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: pull-request, autorelease: pending

#506 chore: release 2.11.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#512 chore: release 2.12.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#523 chore: release 2.13.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending
